title: SigEnergy with EMHASS + Amber Electric for Home Assistant
description: Step-by-step guide to setting up your SigEnergy battery system with Home Assistant using EMHASS and Amber Electric's live prices in Australia.
baseurl: ""
url: "https://sigenergy.annable.me"
theme: minima
minima:
  skin: auto
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
nav:
  - title: "Home"
    url: /
  - title: "Architecture"
    url: /pages/architecture.html
  - title: "Prerequisites"
    url: /pages/prerequisites.html
  - title: "Step-by-step Setup"
    url: /pages/setup.html
  - title: "Running EMHASS"
    url: /pages/emhass.html
  - title: "Automation"
    url: /pages/automation.html
highlighter: rouge
rouge:
  theme: monokai
